# Generated by Django 6.1 on 2026-08-17 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FplDataCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fpl_team_id', models.PositiveIntegerField()),
                ('resource_type', models.CharField(max_length=32)),
                ('gw', models.PositiveIntegerField(blank=True, null=True)),
                ('payload', models.JSONField()),
                ('fetched_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('fpl_team_id', 'resource_type', 'gw'), name='unique_fpl_data_cache_entry')],
            },
        ),
    ]
